### PR TITLE
I ran into the issue that Google wanted to have an api key. I, therefore, added an optional parameter to teh draw method that will add such a key to the html output.

### PR DESCRIPTION
**Pull request by hdzierz**

### CODE REVIEW

**Comment by DakotaHoosier** [comment]
I'd like to see this change.

**Comment by sandrotosi** [comment]
this would expose your API key in the HTML you're going to publish...

**Comment by DakotaHoosier** [comment]
Already a problem at line [#239 in gmplot.py](https://github.com/vgm64/gmplot/blob/master/gmplot/gmplot.py#L240)
```
        f.write('<title>Google Maps - gmplot </title>\n')
        if self.apikey:
            f.write('<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=visualization&sensor=true_or_false&key=%s"></script>\n' % self.apikey )
        else:
            f.write('<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=visualization&sensor=true_or_false"></script>\n' )
        f.write('<script type="text/javascript">\n')
```

**Comment by sandrotosi** [comment]
I think this has been addressed by #111

**Pull request closed without merging**
