### PR TITLE
use 'gmplot' in the HTML page title

### PR DESCRIPTION
**Pull request by sandrotosi**

### CODE REVIEW

**Comment by sandrotosi** [comment]
@vgm64 ping

**Comment by CHBresser** [comment]
Not vgm64, but this will never get accepted, it changes the default. 

A more graceful option may be to allow passage of a title with the default being what it is now, and then if you supply the parameter then it would change.

**Comment by sandrotosi** [comment]
let @vgm64 decide what will or will not be accepted

**Comment by CHBresser** [comment]
Suit yourself. Seeing as it has been over a year, I wouldn't keep your hopes up.

**Comment by sandrotosi** [comment]
you're not adding much value to the discussion, you know right? there are other PRs still open since 2 years; absence of comment is not equivalent to rejection

**Comment by CHBresser** [comment]
I added a separate opinion, I also suggested what you could do to make it more versatile

> A more graceful option may be to allow passage of a title with the default being what it is now, and then if you supply the parameter then it would change.

**Comment by sandrotosi** [comment]
already fixed in https://github.com/gmplot/gmplot/commit/ad6df42e96f9c3accefe691212af06376706f96e

**Pull request closed without merging**
