### PR TITLE
Infowindow

### PR DESCRIPTION
**Pull request by sandrotosi**

### CODE REVIEW

**Comment by sandrotosi** [comment]
@vgm64 ping

**Comment by shpkim** [comment]
Hi, I am having trouble displaying the "contents" in the InfoWindow.

--
gmap = gmplot.GoogleMapPlotter(37.428, -122.145, 15)
gmap.marker(37.428, -122.145, 'r')
contents = "show content"
gmap.infowindow(contents, 37.428, -122.14)
gmap.draw('map.html')
--

I can see an InfoWindow but no contents.
What am I doing wrong here?

Thanks.

**Comment by sandrotosi** [comment]
you have to make the content of `contents` a string, so

```
contents = "'show content'"
```

(note the additional quotes araund show content), anyway it doesnt look like this will be merged anytime soon

**Comment by shpkim** [comment]
Ah, thank you for the explanation!

**Comment by sandrotosi** [comment]
updated at https://github.com/gmplot/gmplot/pull/125

**Pull request closed without merging**
